### ISSUE TITLE
error while running run exp_setup.m

### ISSUE THREAD

**Issue by NerminSalem** [aravindhm/nnpreimage#1]
when i run run exp_setup.m i got the following error
![error](https://cloud.githubusercontent.com/assets/26221951/25369524/c7fb76c0-2984-11e7-8e52-70db9b9d25ab.jpg)
can u help? thanks

**Comment by aravindhm** [comment]
exp_setup runs a shell script to download files etc. That is written for linux. Sorry!

**Comment by NerminSalem** [comment]
Ohhh i got it so i have to had a matlab on linux to run it,right?

**Comment by NerminSalem** [comment]
Also can i use this moddle for vgg19 instead of vgg16 as i saw the defined models and didn't find vgg19
Thanks alot for your kindness in replying my many questions

**Comment by aravindhm** [comment]
No problem. 

You will need matlab if you run it in linux. You can alternatively perform the script operations manually. 
That is download and copy the models into `experiments/networks/` 

Yes, it should work with VGG-19. Remember to run the `get_neuron_stats` using the imagenet dataset for VGG-19.

**Comment by NerminSalem** [comment]
hii
when i tried to run get_neurons_sats i got the following error
Make sure that ILSVRC data is correctly installed in datasets\ILSVRC2012
is this means i have to download the images of ILSVRC2012 training sets which is 147.90GB 
Is this right?

**Comment by aravindhm** [comment]
Yep. In its current form that is what it wants - ILSVRC2012 . It uses every 1000'th image so you can in practice replace it with less data and modify the code accordingly.

**Comment by NerminSalem** [comment]
Ok thanks alot

**Comment by dakkaynak** [comment]
Hi, trying to run your code to see what happens in fc7. So far no luck. Just noting that there is a local dependency in exp_hog '/media/data/aravindh/CVPR2015/objtree/data/vhog-inria-person/model.mat'
