### ISSUE TITLE
get_neuron_stats error

### ISSUE THREAD

**Issue by NerminSalem** [aravindhm/nnpreimage#2]
Hi
 can i run get_neuron_stats using cpu only as my laptop does't support nividia ? @aravindhm  your help is really appreciated

**Comment by aravindhm** [comment]
Please try uncommentng lines 33, 43 and 64 and see if that works?

**Comment by aravindhm** [comment]
Did it work?

**Comment by NerminSalem** [comment]
No unfortunallty it didn't work
Thanks for yr reply
